# -*- coding: utf-8 -*-

LANGUAGES = {u"Abkhaz" : "abk",
             u"Adyghe" : "ady",
             u"Afrikaans" : "afr",
             u"Ainu" : "ain",
             u"Albanian" : "sqi",
             u"Algerian Arabic" : "arq",
             u"Amharic" : "amh",
             u"Ancient Greek" : "grc",
             u"Arabic" : "ara",
             u"Aragonese" : "arg",
             u"Armenian" : "hye",
             u"Assamese" : "asm",
             u"Asturian" : "ast",
             u"Awadhi" : "awa",
             u"Aymara" : "aym",
             u"Azerbaijani" : "aze",
             u"Bambara" : "bam",
             u"Bashkir" : "bak",
             u"Basque" : "eus",
             u"Belarusian" : "bel",
             u"Bengali" : "ben",
             u"Berber" : "ber",
             u"Bhojpuri" : "bho",
             u"Bodo" : "brx",
             u"Bosnian" : "bos",
             u"Breton" : "bre",
             u"Bulgarian" : "bul",
             u"Burmese" : "mya",
             u"Buryat" : "bua",
             u"Cantonese" : "yue",
             u"Catalan" : "cat",
             u"Cebuano" : "ceb",
             u"Central Dusun" : "dtp",
             u"Chamorro" : "cha",
             u"Chavacano" : "cbk",
             u"Chechen" : "che",
             u"Cherokee" : "chr",
             u"Chinese (Mandarin)" : "cmn",
             u"Chinyanja" : "nya",
             u"Choctaw" : "cho",
             u"Chukchi" : "ckt",
             u"Chuvash" : "chv",
             u"Coastal Kadazan" : "kzj",
             u"Cornish" : "cor",
             u"Corsican" : "cos",
             u"Crimean Tatar" : "crh",
             u"Croatian" : "hrv",
             u"Cuyonon" : "cyo",
             u"CycL" : "cycl",
             u"Czech" : "ces",
             u"Danish" : "dan",
             u"Dungan" : "dng",
             u"Dutch" : "nld",
             u"Egyptian Arabic" : "arz",
             u"Emilian" : "egl",
             u"English" : "eng",
             u"Erzya" : "myv",
             u"Esperanto" : "epo",
             u"Estonian" : "est",
             u"Ewe" : "ewe",
             u"Faroese" : "fao",
             u"Fiji Hindi" : "hif",
             u"Fijian" : "fij",
             u"Finnish" : "fin",
             u"French" : "fra",
             u"Frisian" : "fry",
             u"Friulian" : "fur",
             u"Gagauz" : "gag",
             u"Galician" : "glg",
             u"Garhwali" : "gbm",
             u"Georgian" : "kat",
             u"German" : "deu",
             u"Gilbertese" : "gil",
             u"Greek" : "ell",
             u"Greenlandic" : "kal",
             u"Guarani" : "grn",
             u"Guerrero Nahuatl" : "ngu",
             u"Gujarati" : "guj",
             u"Haitian Creole" : "hat",
             u"Hakka Chinese" : "hak",
             u"Hausa" : "hau",
             u"Hawaiian" : "haw",
             u"Hebrew" : "heb",
             u"Hiligaynon" : "hil",
             u"Hill Mari" : "mrj",
             u"Hindi" : "hin",
             u"Hmong Njua" : "hnj",
             u"Ho" : "hoc",
             u"Hungarian" : "hun",
             u"Iban" : "iba",
             u"Icelandic" : "isl",
             u"Ido" : "ido",
             u"Igbo" : "ibo",
             u"Ilocano" : "ilo",
             u"Indonesian" : "ind",
             u"Interlingua" : "ina",
             u"Interlingue" : "ile",
             u"Iraqi Arabic" : "acm",
             u"Irish" : "gle",
             u"Italian" : "ita",
             u"Japanese" : "jpn",
             u"Javanese" : "jav",
             u"Juhuri (Judeo-Tat)" : "jdt",
             u"Kalmyk" : "xal",
             u"Kamba" : "kam",
             u"Kannada" : "kan",
             u"Kapampangan" : "pam",
             u"Karachay-Balkar" : "krc",
             u"Karakalpak" : "kaa",
             u"Kashubian" : "csb",
             u"Kazakh" : "kaz",
             u"Khakas" : "kjh",
             u"Khasi" : "kha",
             u"Khmer" : "khm",
             u"Kinyarwanda" : "kin",
             u"Klingon" : "tlh",
             u"Kölsch" : "ksh",
             u"Korean" : "kor",
             u"Kotava" : "avk",
             u"Kumyk" : "kum",
             u"Kurdish" : "kur",
             u"Kyrgyz" : "kir",
             u"Ladin" : "lld",
             u"Ladino" : "lad",
             u"Lakota" : "lkt",
             u"Lao" : "lao",
             u"Latin" : "lat",
             u"Latvian" : "lvs",
             u"Laz" : "lzz",
             u"Lingala" : "lin",
             u"Lingua Franca Nova" : "lfn",
             u"Literary Chinese" : "lzh",
             u"Lithuanian" : "lit",
             u"Livonian" : "liv",
             u"Lojban" : "jbo",
             u"Lombard" : "lmo",
             u"Louisiana Creole" : "lou",
             u"Low Saxon" : "nds",
             u"Lower Sorbian" : "dsb",
             u"Luganda" : "lug",
             u"Luxembourgish" : "ltz",
             u"Macedonian" : "mkd",
             u"Malagasy" : "mlg",
             u"Malay" : "zsm",
             u"Malayalam" : "mal",
             u"Maltese" : "mlt",
             u"Mambae" : "mgm",
             u"Manx" : "glv",
             u"Maori" : "mri",
             u"Marathi" : "mar",
             u"Marshallese" : "mah",
             u"Meadow Mari" : "mhr",
             u"Middle English" : "enm",
             u"Middle French" : "frm",
             u"Min Nan Chinese" : "nan",
             u"Mohawk" : "moh",
             u"Moksha" : "mdf",
             u"Mon" : "mnw",
             u"Mongolian" : "mon",
             u"Moroccan Arabic" : "ary",
             u"Nahuatl" : "nah",
             u"Navajo" : "nav",
             u"Nepali" : "npi",
             u"Ngeq " : "ngt",
             u"Nigerian Fulfulde" : "fuv",
             u"Niuean" : "niu",
             u"Nogai" : "nog",
             u"North Levantine Arabic" : "apc",
             u"North Moluccan Malay" : "max",
             u"Northern Sami" : "sme",
             u"Norwegian (Bokmål)" : "nob",
             u"Norwegian (Nynorsk)" : "nno",
             u"Novial" : "nov",
             u"Occitan" : "oci",
             u"Odia (Oriya)" : "ori",
             u"Ojibwe" : "oji",
             u"Old Aramaic" : "oar",
             u"Old East Slavic" : "orv",
             u"Old English" : "ang",
             u"Old Norse" : "non",
             u"Old Prussian" : "prg",
             u"Old Saxon" : "osx",
             u"Old Tupi" : "tpw",
             u"Orizaba Nahuatl" : "nlv",
             u"Ossetian" : "oss",
             u"Ottoman Turkish" : "ota",
             u"Palatine German" : "pfl",
             u"Palauan" : "pau",
             u"Pangasinan" : "pag",
             u"Papiamento" : "pap",
             u"Pashto" : "pus",
             u"Pennsylvania German" : "pdc",
             u"Persian" : "pes",
             u"Picard" : "pcd",
             u"Piedmontese" : "pms",
             u"Pipil" : "ppl",
             u"Polish" : "pol",
             u"Portuguese" : "por",
             u"Pulaar" : "fuc",
             u"Punjabi (Eastern)" : "pan",
             u"Punjabi (Western)" : "pnb",
             u"Quechua" : "que",
             u"Quenya" : "qya",
             u"Romani" : "rom",
             u"Romanian" : "ron",
             u"Romansh" : "roh",
             u"Russian" : "rus",
             u"Samoan" : "smo",
             u"Sango" : "sag",
             u"Sanskrit" : "san",
             u"Sardinian" : "srd",
             u"Scots" : "sco",
             u"Scottish Gaelic" : "gla",
             u"Serbian" : "srp",
             u"Setswana" : "tsn",
             u"Seychellois Creole" : "crs",
             u"Shanghainese" : "wuu",
             u"Shona" : "sna",
             u"Shuswap" : "shs",
             u"Sicilian" : "scn",
             u"Sindarin" : "sjn",
             u"Sindhi" : "snd",
             u"Sinhala" : "sin",
             u"Slovak" : "slk",
             u"Slovenian" : "slv",
             u"Somali" : "som",
             u"Southern Altai" : "alt",
             u"Southern Sotho" : "sot",
             u"Spanish" : "spa",
             u"Sumerian" : "sux",
             u"Sundanese" : "sun",
             u"Swahili" : "swh",
             u"Swedish" : "swe",
             u"Swiss German" : "gsw",
             u"Tagal Murut" : "mvv",
             u"Tagalog" : "tgl",
             u"Tajik" : "tgk",
             u"Tamil" : "tam",
             u"Tarifit" : "rif",
             u"Tatar" : "tat",
             u"Telugu" : "tel",
             u"Tetun" : "tet",
             u"Thai" : "tha",
             u"Tibetan" : "bod",
             u"Tigrinya" : "tir",
             u"Tok Pisin" : "tpi",
             u"Tokelauan" : "tkl",
             u"Toki Pona" : "toki",
             u"Tongan" : "ton",
             u"Tsonga" : "tso",
             u"Turkish" : "tur",
             u"Turkmen" : "tuk",
             u"Tuvinian" : "tyv",
             u"Udmurt" : "udm",
             u"Ukrainian" : "ukr",
             u"Umbundu" : "umb",
             u"Upper Sorbian" : "hsb",
             u"Urdu" : "urd",
             u"Urhobo" : "urh",
             u"Uyghur" : "uig",
             u"Uzbek" : "uzb",
             u"Venetian" : "vec",
             u"Vietnamese" : "vie",
             u"Volapük" : "vol",
             u"Võro" : "vro",
             u"Walloon" : "wln",
             u"Waray" : "war",
             u"Welsh" : "cym",
             u"Wolof" : "wol",
             u"Xhosa" : "xho",
             u"Yakut" : "sah",
             u"Yiddish" : "yid",
             u"Yoruba" : "yor",
             u"Zaza" : "zza",
             "Zulu" : "zul"}
